/**
 * actionTypes
 */

export const GET_BIKE_LANES = 'GET_BIKE_LANES'
export const GET_BIKE_LANES_SUCCESS = 'GET_BIKE_LANES_SUCCESS'
export const GET_BIKE_LANES_ERROR = 'GET_BIKE_LANES_ERROR'
export const CLEAR_BIKE_LANES = 'CLEAR_BIKE_LANES'

export const UPDATE_SELECTED_DATA = 'UPDATE_SELECTED_DATA'
export const GET_NEAR_BY_STATION = 'GET_NEAR_BY_STATION'
export const GET_NEAR_BY_STATION_SUCCESS = 'GET_NEAR_BY_STATION_SUCCESS'
export const GET_NEAR_BY_STATION_ERROR = 'GET_NEAR_BY_STATION_ERROR'
